DATABASE_HOST = 'localhost'
DATABASE_NAME = 'DATABASE_NAME'
DB_USER = 'USER_NAME'
DB_PASSWORD = 'USER_PASSWORD'

EMAIL_SERVER = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_ID = 'YOUR_EMAIL_ID'
EMAIL_PASS = 'YOUR_EMAIL_PASS'

TWILIO_ACCOUNT_SID = 'YOUR_ACCOUNT_SID'
TWILIO_AUTH_TOKEN = 'YOUR_ACCOUNT_AUTH_TOKEN'
TWILIO_NUMBER = 'YOUR_TWILIO_NUMBER'